// Date: 22.06.2016 15:46:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package lellson.expandablebackpack.misc.models;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBackpack extends ModelBiped {
	
	ModelRenderer CubeMain;
	ModelRenderer CubeFront;
	ModelRenderer CubeLeft;
	ModelRenderer CubeRight;

	public ModelBackpack(float expand) {
		
		super(expand, 0, 64, 64);

		CubeMain = new ModelRenderer(this, 22, 49);
		CubeMain.addBox(0F, 0F, 0F, 8, 11, 4);
      	CubeMain.setRotationPoint(-4F, 1F, 2F);
      	CubeMain.setTextureSize(64, 64);
      	CubeMain.mirror = true;
      	setRotation(CubeMain, 0F, 0F, 0F);
      	
      	CubeFront = new ModelRenderer(this, 8, 58);
      	CubeFront.addBox(0F, 0F, 0F, 6, 5, 1);
      	CubeFront.setRotationPoint(-3F, 6F, 6F);
      	CubeFront.setTextureSize(64, 64);
      	CubeFront.mirror = true;
      	setRotation(CubeFront, 0F, 0F, 0F);
      	
      	CubeLeft = new ModelRenderer(this, 0, 57);
      	CubeLeft.addBox(0F, 0F, 0F, 1, 4, 3);
      	CubeLeft.setRotationPoint(4F, 7F, 2F);
      	CubeLeft.setTextureSize(64, 64);
      	CubeLeft.mirror = true;
      	setRotation(CubeLeft, 0F, 0F, 0F);
      	
      	CubeRight = new ModelRenderer(this, 0, 57);
      	CubeRight.addBox(0F, 0F, 0F, 1, 4, 3);
      	CubeRight.setRotationPoint(-5F, 7F, 2F);
      	CubeRight.setTextureSize(64, 64);
      	CubeRight.mirror = true;
      	setRotation(CubeRight, 0F, 0F, 0F);
		
		this.bipedBody.addChild(CubeMain);
		this.bipedBody.addChild(CubeFront);
		this.bipedBody.addChild(CubeLeft);
		this.bipedBody.addChild(CubeRight);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
